{"name": "test_demo_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(2)", "trace": "self = <test_pytest.TestWuhan2021 object at 0x00000000033A6D30>\n\n    @pytest.mark.fail\n    def test_demo_2(self):\n>       assert inc(2) == 4\nE       assert 3 == 4\nE        +  where 3 = inc(2)\n\nstudy_pytest\\test_pytest.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "ef1bccd9-3ab8-44c6-8cb5-a5fbd5435a14-attachment.txt", "type": "text/plain"}], "start": 1613204101689, "stop": 1613204101689, "uuid": "58117a3c-accf-43dd-9cde-2cd5fd9181b9", "historyId": "2ca0144722daa38050859b135de24376", "testCaseId": "64f43b606970e0e86fdf6dde25f2d505", "fullName": "study_pytest.test_pytest.TestWuhan2021#test_demo_2", "labels": [{"name": "tag", "value": "fail"}, {"name": "parentSuite", "value": "study_pytest"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestWuhan2021"}, {"name": "host", "value": "PC-20200703UCXE"}, {"name": "thread", "value": "10036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study_pytest.test_pytest"}]}